version: '3.8'
services:
    prytaneum-server:
        build:
            context: .
            target: base-stage
        volumes:
            - ./src:/usr/app/src
            - ./package.json:/usr/app/package.json
            - ./yarn.lock:/usr/app/yarn.lock
            - ./.babelrc:/usr/app/.babelrc
            - ./.env:/usr/app/.env
        command: yarn start
        ports:
            - 3000:3000
        depends_on:
            - mongo
        tty: true
    mongo:
        image: mongo:4.2.8-bionic
        ports:
          - 3001:27017
