name: Deploy

on:
    # Trigger the workflow on push or pull request,
    # but only for the main branch
    push:
        branches:
            - master

env:
    BUILD_ID: ${{ secrets.GCP_SERVER }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REPOSITORY }}/${{ secrets.GCP_IMAGE }}:$GITHUB_SHA
jobs:
    docker-push:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Make envfile
              uses: SpicyPizza/create-envfile@v1
              with:
                  envkey_ORIGIN: ${{ secrets.ORIGIN }}
                  envkey_PORT: ${{ secrets.PORT }}
                  envkey_NODE_ENV: ${{ secrets.NODE_ENV }}
                  envkey_DB_URL: ${{ secrets.DB_URL }}
                  envkey_JWT_SECRET: ${{ secrets.JWT_SECRET }}
                  envkey_COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}
                  file_name: .env
                  
            - name: Set up QEMU
              if: ${{ !env.ACT }}
              uses: docker/setup-qemu-action@v1

            - name: Set up Docker Buildx
              if: ${{ !env.ACT }}
              uses: docker/setup-buildx-action@v1

            # - name: Login to GAR
            #   if: ${{ !env.ACT }}
            #   uses: docker/login-action@v1
            #   with:
            #       registry: us-west2-docker.pkg.dev
            #       username: gar-720
            #       password: ${{ secrets.GAR_JSON_KEY }}

            - name: Setup gcloud
              uses: google-github-actions/setup-gcloud@v0.2.0
              with:
                  project_id: ${{ secrets.GCP_PROJECT_ID }}
                  service_account_key: ${{ secrets.GAR_JSON_KEY }}
                  export_default_credentials: true

            - name: Build
              run: docker build -t ${{ secrets.GCP_SERVER }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REPOSITORY }}/${{ secrets.GCP_IMAGE }}:$GITHUB_SHA .

            - name: Configure gcloud and push
              run: |
                  gcloud auth configure-docker us-west2-docker.pkg.dev
                  docker push ${{ secrets.GCP_SERVER }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REPOSITORY }}/${{ secrets.GCP_IMAGE }}:$GITHUB_SHA
